### ISSUE TITLE
Question - Does it have prerelease support?

### ISSUE THREAD

**Issue by PauloGoncalvesBH** [esatterwhite/semantic-release-docker#16]
I'm looking for a semantic-release docker library that allows every release generated from the 'trunk' branch to generate an image tagged latest, and published in the 'beta' branch generate it with a beta tag and with the x.x.x-beta version. (example: 3.4.1-beta.1).

---

My release configuration is as follows: 

https://github.com/ServeRest/ServeRest/blob/d30fcf68d7fe39d4f4f04917ed00ec43b7eb766c/.releaserc.js#L74

This page shows the releases and some generated beta pre-releases:

https://github.com/ServeRest/ServeRest/releases?page=2

**Comment by esatterwhite** [comment]
@PauloGoncalvesBH I can't say that I've tried it, but I don't see why it wouldn't as long as semantic release does what it normally does. 

by default there is a templated tag that is just `{version}` which is passed through by semantic release. if it still does that - it _should_ work

**Comment by infiniityr** [comment]
I try to tag the images differently if it is a pre-release but the `nextRelease.version` doesn't seems to exists.
I also tried with `version` and `next.version`, I got the same results : the release tags are used.

```javascript
module.exports = {
  plugins: [
    [
      '@semantic-release/git',
      {
        assets: [
          'package.json'
        ],
        message: "chore(release): ${nextRelease.version} [skip ci]\n\n${nextRelease.notes}"
      }
    ],
   [
      '@codedependant/semantic-release-docker',
      {
        dockerTags: "${nextRelease.version}".includes('sprint') ? ['beta', '{version}', '{major}-beta', '{major}.{minor}-beta'] : ['latest', '{version}', '{major}-latest', '{major}.{minor}'],
        dockerImage: 'image',
        dockerRegistry: 'my-registry.net',
        dockerProject: 'project',
        dockerLogin: false,
        dockerPublish: true
      }
    ]
  ]
}
```

**Comment by esatterwhite** [comment]
You are using the string literal `"${nextRelease.version}"` which does not include the string `sprint`. Docker tags isn't a lodash template, the template engine is very basic but could be expanded. Additionally, the JavaScript ternary is executed when the module is loaded rather than when the plugin is executed. So this will likely never work. 

It seems like you are looking for some conditional processing?

```js
{
  dockerTags: ["{#if prerelease}beta{/if}" ]
}
```

**Comment by infiniityr** [comment]
Indeed, i'm looking at this kind of preprocessing or maybe a custom function for the creation of the configuration.

**Comment by esatterwhite** [comment]
I think its pretty doable to swap out handlebars as the template engine and pre load some string helpers. and expose an option to specify additional helper functions. Then you can pretty much do what you want here.

**Comment by infiniityr** [comment]
It works perfectly ! 

Here is the solution using Handlebars

```javascript
module.exports = {
  plugins: [
    [
      '@semantic-release/git',
      {
        assets: [
          'package.json'
        ],
        message: "chore(release): ${nextRelease.version} [skip ci]\n\n${nextRelease.notes}"
      }
    ],
   [
      '@codedependant/semantic-release-docker',
      {
        dockerTags: ['{{version}}', "{{#if (includes version 'sprint')}}beta{{else}}latest{{/if}}", "{{major}}-{{#if (includes version 'sprint')}}beta{{else}}latest{{/if}}", "{{major}}.{{minor}}{{#if (includes version 'sprint')}}-beta{{/if}}"],
        dockerImage: 'image',
        dockerRegistry: 'my-registry.net',
        dockerProject: 'project',
        dockerLogin: false,
        dockerPublish: true
      }
    ]
  ]
}
```

Thank you for the release ! :D
