### ISSUE TITLE
Enable using podman instead docker

### ISSUE THREAD

**Issue by mchraa** [esatterwhite/semantic-release-docker#32]
**Context**
I'm trying to use podman to build the image using this plugin. A ln is set and podman is used instead of the docker command to build the image. 

The build command fails because the podman don't log out the sha digest in the same way as docker.
In podman the digest is in one line without the "Digest:" part. 

**Current behaviour**
If there is no ":" in the build output an exception is thrown:
`[7:22:45 AM] [semantic-release] › ✖  An error occurred while running semantic-release: TypeError: Cannot read properties of undefined (reading 'substring')
    at Image.build (.../node_modules/@codedependant/semantic-release-docker/lib/docker/image.js:123:20)`

**Expected behaviour**
If no sha is parsed, it shall not throws an exception and continue.

**Comment by esatterwhite** [comment]
I think that is outside the scope of this plugin. That needs to be its own plugin
