### ISSUE TITLE
Command failed with exit code 123: xargs docker rmi -f

### ISSUE THREAD

**Issue by denispeyrusaubes** [esatterwhite/semantic-release-docker#34]
Hi,

Trying to use semantic-release from a Jenkins pipeline.

I get this :

```
[7:49:07 AM] [semantic-release] › ✖  Failed step "fail" of plugin "@codedependant/semantic-release-docker"
[7:49:07 AM] [semantic-release] › ✖  An error occurred while running semantic-release: Error: Command failed with exit code 123: xargs docker rmi -f
"docker rmi" requires at least 1 argument.
See 'docker rmi --help'.

Usage:  docker rmi [OPTIONS] IMAGE [IMAGE...]

Remove one or more images
    at makeError (/usr/local/lib/node_modules/@codedependant/semantic-release-docker/node_modules/execa/lib/error.js:59:11)
```

I can understand that my image shall be removed after being build and published. But I see no where any message concerning the build nore the publication... 

Any idea ?

**Comment by jamesrusso** [comment]
Having the same issue running in guthub action. I'm not convinced that I even need to do any cleanup. I'm building, publishing to ECR. I don't think I need to remove them from a local docker instance since the github actions docker instance is likely temporary for the lifetime of the build anyways?

**Comment by esatterwhite** [comment]
@denispeyrusaubes Is there any error before these lines?
It looks like the build of the image didn't succeed in the first place, and rmi is failing because there is no image/tag to remove.

I could make the clean a little more forgiving and not kill the build. or make the autoclean and option. or both.

**Comment by esatterwhite** [comment]
@jamesrusso @denispeyrusaubes There is the `dockerAutoClean` option as of [v4.3.0](https://github.com/esatterwhite/semantic-release-docker/releases/tag/v4.3.0) which you can set to false to disable the bit that tries to remove the images
