### ISSUE TITLE
Support for --cache-from argument, or custom docker cli arguments

### ISSUE THREAD

**Issue by yevon** [esatterwhite/semantic-release-docker#35]
Is it possible to specify the --cache-from docker argument to speed up the build speed in pipelines? Or specify other docker params outside build-args? I haven't seen this in the docs, thanks!

I have been using this plugin recently and is working very nicely.

**Comment by esatterwhite** [comment]
I think no in both cases. but it wouldn't be hard to allow for `dockerArgs: []`

**Comment by Dextererials** [comment]
> Is it possible to specify the --cache-from docker argument to speed up the build speed in pipelines? Or specify other docker params outside build-args? I haven't seen this in the docs, thanks!
> 
> I have been using this plugin recently and is working very nicely.

The ability to provide params for docker would be great. Currently trying to pass a secret and there is no way to do this that I can see

**Comment by esatterwhite** [comment]
I see, could you post an example command?

**Comment by Dextererials** [comment]
Yes. For example `docker build --secret id=ssh,src=~/.ssh/id_rsa --tag $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA .`

**Comment by esatterwhite** [comment]
@Dextererials Sorry for letting this sit so long. I'll take a look at it this week

**Comment by esatterwhite** [comment]
@yevon @Dextererials Would you expect this to accept template placeholders?

**Comment by yevon** [comment]
Tested yesterday, working nicely thanks!

**Comment by Dextererials** [comment]
Just tested on my end as well and works great. Thank you!
