### ISSUE TITLE
Multi-Platform Docker builds

### ISSUE THREAD

**Issue by Lateralus58** [esatterwhite/semantic-release-docker#39]
Is there any potential to support multi-platform docker builds with buildx?

**Comment by esatterwhite** [comment]
ya, it has been coming up a lot lately. I'm a little torn as buildx behaves much differently than build. They aren't really interchangeable.

**Comment by esatterwhite** [comment]
Mainly there isn't a clear separation between build and push. It all kind of happens in a single operation.

**Comment by arvinxx** [comment]
So is there any why to build arm64 image with semantic-release-docker ？

**Comment by esatterwhite** [comment]
It's probably possible, it just need to be sorted out. The semantic release steps have a separation between build and publish, so that will be a little problematic. I'm haven't looked into that with multi arch builds yet
