### ISSUE TITLE
Add `cache-to` argument

### ISSUE THREAD

**Issue by oSumAtrIX** [esatterwhite/semantic-release-docker#55]
Currently, only the argument to specify a cache is present. But there is no argument to cache.  The action https://github.com/docker/build-push-action has such an argument and could be used as a reference.

**Comment by esatterwhite** [comment]
@oSumAtrIX is this something that could be solved with [dockerBuildFlags](https://github.com/esatterwhite/semantic-release-docker?tab=readme-ov-file#example)

**Comment by oSumAtrIX** [comment]
I am not sure but probably it is possible. I was thinking it would make sense to introduce `cache-to` to it's existent counterpart `cache-from`, because the latter only makes sense with the former

**Comment by esatterwhite** [comment]
It makes sense to me. But in the short term if this is holding you up or preventing you from using the plugin, it's likely a 1 line config change. 

Internally cache-from is just a short cut to dockerBuildFlags. 

https://github.com/esatterwhite/semantic-release-docker/blob/3ae65248bb860e5597db0637a99e7e841b9b27df/lib/build-config.js#L49

**Comment by oSumAtrIX** [comment]
Why would you add `cache-from` but not the counterpart `cache-to`? The shortcut was intended to prevent having to use dockerBuildFlags yourself, but because there's no `cache-to` that does not make sense anymore as you now have to use dockerBuildFlags anyway.

**Comment by esatterwhite** [comment]
Someone had a use case for cache-from at the time and the build args bit didn't exist then.it was ported over when the new thing was added. I don't really intend to remap everything that docker exposes when there is a way to add whatever you need ad-hoc

**Comment by oSumAtrIX** [comment]
cache-from and cache-to are very common in actions such as this. If someone intended to use cache-from like you said, why would they not want cache-to? If you think dockerBuildFlags should be used for cache-to, then cache-from should be deprecated in favour of it as well.

**Comment by esatterwhite** [comment]
I'm not quite sure what the issue is @oSumAtrIX. they accomplish the same thing. 

[Here](https://github.com/esatterwhite/semantic-release-docker/issues/35) the original request. Feel free to ask them why they wanted one but not the other.

In the mean time, You are welcome to open a pull request to add the mising option. Or use a different plugin.
