### ISSUE TITLE
docker build --build-arg ...

### ISSUE THREAD

**Issue by sebastiangaiser** [esatterwhite/semantic-release-docker#7]
Hi there,

I'm trying to use your plugin for my workflow, but I'm using some custom build args for my docker images like:

```
docker build --build-arg USER=$USER --build-arg GROUP=$(cat filename) ...
```

Is there a possibility to specify these like here:

```
{
  "release": {
    "plugins": [
      ["@codedependant/semantic-release-docker", {
        "docker": {
          "tags": ["latest", "{version}", "{major}-latest", "{major}.{minor}"],
          "image": "my-image",
          "dockerfile": "Dockerfile",
          "registry": "quay.io",
          "project": "codedependant",
          "build-args": ["USER=$USER", "GROUP=$(cat filename)"]
        }
      }]
    ]
  }
}
```

**Comment by esatterwhite** [comment]
@sebastiangaiser 
yes, sorry, this is a documentation bug.

its `args` not build-args, and its an object.

if you want the value to pick up a matching environment variable you can set the value explicitly to true

```json
{
  "release": {
    "plugins": [
      ["@codedependant/semantic-release-docker", {
        "docker": {
          "tags": ["latest", "{version}", "{major}-latest", "{major}.{minor}"],
          "image": "my-image",
          "dockerfile": "Dockerfile",
          "registry": "quay.io",
          "project": "codedependant",
          "args": {
              "USER": true
          }
        }
      }]
    ]
  }
}
```

As for dynamic shell execution, no. not currently.

**Comment by esatterwhite** [comment]
I'm in the process of flattening the configuration in the next major release #8.
semantic release doesn't handle deep merging of nested objects very well, and can get rather difficult to use like this

**Comment by esatterwhite** [comment]
I'm also adding the ability to template build args like tags. if that help.

What is your use case exactly?

**Comment by esatterwhite** [comment]
Seems stale. Feel free to re-open if the suggestion didn't fix your problem
